apiVersion : apps/v1
kind: Deployment
metadata:
  name: regannetcapstone 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regannetcapstone
  template:
    metadata:
      labels:
        app: regannetcapstone 
    spec:
      containers:
        - name: regannetcapstone 
          image: jumpcapstone.azurecr.io/jumpcaptone
          env:
          - name: ASPNETCORE_ENVIRONMENT 
            value: "Development"
          ports:
          - containerPort: 80
